[build]
command = "npm run build"
publish = "dist"
[functions]
directory = "netlify/functions/"
[dev]
command = "parcel src/index.html"
[[redirects]]
from = "/github-oauth"
status = 200
to = "/.netlify/functions/github-oauth"
[[redirects]]
from = "/cors-proxy"
status = 200
to = "/.netlify/functions/cors-proxy"
[[redirects]]
from = "/authorized/github"
status = 200
to = "/"
[[redirects]]
from = "/*"
status = 200
to = "/"
